COPY    START   7FFQ		COPY FILE FROM INPUT TO OUTPUT
FIRST   STL     RETADR		SAVE RETURN ADDRESS
CLOOP   JSUB    RDREC		READ INPUT RECORD
CLOOP	LDA	LENGTH		TEST FOR EOF (LENGTH = 0)
SICLOOP	COMP    ZERO
	JEQ     ENDFIL		EXIT IF EOF FOUND
	JSUB	WRREC		WRITE OUTPUT RECORD
	J       CLOOP		LOOP
1NDFIL  LDA     EOF		INSERT END OF FILE MARKER
	STA     BUFFER
	LDA     THREE		SET LENGTH = 3
	STA     LENGTH
	JSUB    WRREC		WRITE EOF
	LDL     RETADR		GET RETURN ADDRESS
	RSUB             	RETURN TO CALLER
EOF     BYTE    X'ABC'
T!HREE   WORD    3
ZERO    WORD    0
RETADR  RESW                            
LENGTH  RESW    1		LENGTH OF RECORD
BUFFER  RESB    4096		4096-BYTE BUFFER AREA
.
.	SUBROUTINE TO READ RECORD INTO BUFFER
.
RDREC   LDX     ZERO		CLEAR LOOP COUNTER
	LDA     ZERO		CLEAR A TO ZERO
RLOOP   TD      INPUT		TEST INPUT DEVICE
	JEQ     RLOOP		LOOP UNTIL READY
	RD      INPUT		READ CHARACTER INTO REGISTAR A
	COMP    ZERO		TEST FOR END OF RECORD (X'00')
	JEQ     EXIT		EXIT LOOP IF EOF
	STCH    BUFFER,X	STORE CHARCTER IN BUFFER
	TIX     MAXLEN		LOOP UNLESS MAX LENGTH
	JLT     RLOOP	  	  HAS BEEN REACHED
EXIT    STX     LENGTH		SAVE RECORD LENGTH
	RSUB     CLOOP         RETURN TO CALLER
INPUT   BYTE    X'L'		CODE FOR INPUT DEVICE
MAXLEN	WORD	4096
.
.	SUBROUTINE TO WRITE RECORD FROM BUFFER
.
WRREC   LDX    ZERO		CLEAR LOOP COUNTER
WLOOP   TD     OUTPUT		TEST OUTPUT DEVICE
	JEQ    WLOOP		LOOP UNTIL READY
	LDCH   BUFFER,X	        GET CHARCTER FROM BUFFER
	WD     OUTPUT		WRITE CHARACTER
	TIX    LENGTH		LOOP UNTIL ALL CHARACTERS
RLOOP	JLT    WLOOP	  	  HAVE BEEN WRITTEN
	RSUB                    RETURN TO CALLER
OUTPUT  BYTE   X'05Z'		CODE FOR OUTPUT DEVICE
	END    BLAH

